
import datetime
from twisted.words.protocols.irc import assembleFormattedText, attributes
import lxml.html
from urllib.request import urlopen

from . import plugin

BOM_URL = "http://www.bom.gov.au"

class Weather(plugin.Plugin):

    cached_weather_data = {}

    @plugin.command("w", "weather")
    def weather(self, message):    
        _, _, location_name = message.message.lstrip("!").partition(" ")
        location_url = self.location_urls.get(location_name, None)
        if location_url is not None:
            weather_data = self.cached_weather_data.get(location_name, None)

            if weather_data is None or self.is_weather_data_stale(weather_data):
                weather_data = (datetime.date.today(), self.get_weather(location_name, location_url))
                self.cached_weather_data[location_name] = weather_data

            return weather_data[1]
        else:
            return f"Unkown location: {location_name}"

    def is_weather_data_stale(self, weather_data):
        delta = weather_data[0] - datetime.date.today()
        return delta.days < 0

    def get_weather(self , location_name, location_url):
        html = urlopen(location_url)
        tree = lxml.html.parse(html)

        day_main_element = tree.xpath("//div[@class=\"day main\"]")[0]
        forecast_max_temp = day_main_element.xpath("//em[@class=\"max\"]")[0].text
        forecast_summary = day_main_element.xpath("//dd[@class=\"summary\"]")[0].text

        return assembleFormattedText(
            attributes.normal[attributes.bold[location_name], f" max: {forecast_max_temp} {forecast_summary}"])

    location_urls = {
        "sydney" : "http://www.bom.gov.au/nsw/forecasts/sydney.shtml",
        "cronulla" : "http://www.bom.gov.au/nsw/forecasts/cronulla.shtml",
        "liverpool" : "http://www.bom.gov.au/nsw/forecasts/liverpool.shtml",
        "penrith" : "http://www.bom.gov.au/nsw/forecasts/penrith.shtml",
        "mona vale" : "http://www.bom.gov.au/nsw/forecasts/mona-vale.shtml",
        "mascot" : "http://www.bom.gov.au/nsw/forecasts/mascot.shtml",
        "terrey hills" : "http://www.bom.gov.au/nsw/forecasts/terreyhills.shtml",
        "richmond" : "http://www.bom.gov.au/nsw/forecasts/richmond.shtml",
        "parramatta" : "http://www.bom.gov.au/nsw/forecasts/parramatta.shtml",
        "blacktown" : "http://www.bom.gov.au/nsw/forecasts/blacktown.shtml",
        "camden" : "http://www.bom.gov.au/nsw/forecasts/camden.shtml",
        "campbelltown" : "http://www.bom.gov.au/nsw/forecasts/campbelltown.shtml",
        "canterbury" : "http://www.bom.gov.au/nsw/forecasts/canterbury.shtml",
        "bondi" : "http://www.bom.gov.au/nsw/forecasts/bondi.shtml",
        "hornsby" : "http://www.bom.gov.au/nsw/forecasts/hornsby.shtml",
        "sydney olympic park" : "http://www.bom.gov.au/nsw/forecasts/sydney-olympic-park.shtml",
        "belconnen" : "http://www.bom.gov.au/act/forecasts/belconnen.shtml",
        "gungahlin" : "http://www.bom.gov.au/act/forecasts/gungahlin.shtml",
        "woden valley" : "http://www.bom.gov.au/act/forecasts/woden-valley.shtml",
        "canberra" : "http://www.bom.gov.au/act/forecasts/canberra.shtml",
        "tuggeranong" : "http://www.bom.gov.au/act/forecasts/tuggeranong.shtml",
        "mount ginini" : "http://www.bom.gov.au/act/forecasts/mountginini.shtml",
        "byron bay" : "http://www.bom.gov.au/nsw/forecasts/byronbay.shtml",
        "lismore" : "http://www.bom.gov.au/nsw/forecasts/lismore.shtml",
        "yamba" : "http://www.bom.gov.au/nsw/forecasts/yamba.shtml",
        "grafton" : "http://www.bom.gov.au/nsw/forecasts/grafton.shtml",
        "evans head" : "http://www.bom.gov.au/nsw/forecasts/evans-head.shtml",
        "ballina" : "http://www.bom.gov.au/nsw/forecasts/ballina.shtml",
        "murwillumbah" : "http://www.bom.gov.au/nsw/forecasts/murwillumbah.shtml",
        "tweed heads" : "http://www.bom.gov.au/nsw/forecasts/tweedheads.shtml",
        "coffs harbour" : "http://www.bom.gov.au/nsw/forecasts/coffsharbour.shtml",
        "kempsey" : "http://www.bom.gov.au/nsw/forecasts/kempsey.shtml",
        "port macquarie" : "http://www.bom.gov.au/nsw/forecasts/portmacquarie.shtml",
        "taree" : "http://www.bom.gov.au/nsw/forecasts/taree.shtml",
        "forster" : "http://www.bom.gov.au/nsw/forecasts/forster.shtml",
        "bulahdelah" : "http://www.bom.gov.au/nsw/forecasts/bulahdelah.shtml",
        "barrington tops" : "http://www.bom.gov.au/nsw/forecasts/barrington-tops.shtml",
        "dorrigo" : "http://www.bom.gov.au/nsw/forecasts/dorrigo.shtml",
        "nambucca heads" : "http://www.bom.gov.au/nsw/forecasts/nambucca-heads.shtml",
        "wauchope" : "http://www.bom.gov.au/nsw/forecasts/wauchope.shtml",
        "newcastle" : "http://www.bom.gov.au/nsw/forecasts/newcastle.shtml",
        "maitland" : "http://www.bom.gov.au/nsw/forecasts/maitland.shtml",
        "singleton" : "http://www.bom.gov.au/nsw/forecasts/singleton.shtml",
        "wyong" : "http://www.bom.gov.au/nsw/forecasts/wyong.shtml",
        "cessnock" : "http://www.bom.gov.au/nsw/forecasts/cessnock.shtml",
        "gosford" : "http://www.bom.gov.au/nsw/forecasts/gosford.shtml",
        "woy woy" : "http://www.bom.gov.au/nsw/forecasts/woy-woy.shtml",
        "scone" : "http://www.bom.gov.au/nsw/forecasts/scone.shtml",
        "nelson bay" : "http://www.bom.gov.au/nsw/forecasts/nelson-bay.shtml",
        "toronto" : "http://www.bom.gov.au/nsw/forecasts/toronto.shtml",
        "wallsend" : "http://www.bom.gov.au/nsw/forecasts/wallsend.shtml",
        "the entrance" : "http://www.bom.gov.au/nsw/forecasts/entrance.shtml",
        "raymond terrace" : "http://www.bom.gov.au/nsw/forecasts/raymond-terrace.shtml",
        "muswellbrook" : "http://www.bom.gov.au/nsw/forecasts/muswellbrook.shtml",
        "walcha" : "http://www.bom.gov.au/nsw/forecasts/walcha.shtml",
        "armidale" : "http://www.bom.gov.au/nsw/forecasts/armidale.shtml",
        "inverell" : "http://www.bom.gov.au/nsw/forecasts/inverell.shtml",
        "glen innes" : "http://www.bom.gov.au/nsw/forecasts/gleninnes.shtml",
        "tenterfield" : "http://www.bom.gov.au/nsw/forecasts/tenterfield.shtml",
        "guyra" : "http://www.bom.gov.au/nsw/forecasts/guyra.shtml",
        "bulli" : "http://www.bom.gov.au/nsw/forecasts/bulli.shtml",
        "port kembla" : "http://www.bom.gov.au/nsw/forecasts/port-kembla.shtml",
        "bowral" : "http://www.bom.gov.au/nsw/forecasts/bowral.shtml",
        "nowra" : "http://www.bom.gov.au/nsw/forecasts/nowra.shtml",
        "huskisson" : "http://www.bom.gov.au/nsw/forecasts/huskisson.shtml",
        "albion park" : "http://www.bom.gov.au/nsw/forecasts/albionpark.shtml",
        "wollongong" : "http://www.bom.gov.au/nsw/forecasts/wollongong.shtml",
        "kiama" : "http://www.bom.gov.au/nsw/forecasts/kiama.shtml",
        "batemans bay" : "http://www.bom.gov.au/nsw/forecasts/batemansbay.shtml",
        "narooma" : "http://www.bom.gov.au/nsw/forecasts/narooma.shtml",
        "bega" : "http://www.bom.gov.au/nsw/forecasts/bega.shtml",
        "merimbula" : "http://www.bom.gov.au/nsw/forecasts/merimbula.shtml",
        "monolith valley" : "http://www.bom.gov.au/nsw/forecasts/monolith-valley.shtml",
        "ulladulla" : "http://www.bom.gov.au/nsw/forecasts/ulladulla.shtml",
        "eden" : "http://www.bom.gov.au/nsw/forecasts/eden.shtml",
        "orange" : "http://www.bom.gov.au/nsw/forecasts/orange.shtml",
        "mudgee" : "http://www.bom.gov.au/nsw/forecasts/mudgee.shtml",
        "bathurst" : "http://www.bom.gov.au/nsw/forecasts/bathurst.shtml",
        "lithgow" : "http://www.bom.gov.au/nsw/forecasts/lithgow.shtml",
        "katoomba" : "http://www.bom.gov.au/nsw/forecasts/katoomba.shtml",
        "springwood" : "http://www.bom.gov.au/nsw/forecasts/springwood.shtml",
        "wellington" : "http://www.bom.gov.au/nsw/forecasts/wellington.shtml",
        "jenolan caves" : "http://www.bom.gov.au/nsw/forecasts/jenolan-caves.shtml",
        "goulburn" : "http://www.bom.gov.au/nsw/forecasts/goulburn.shtml",
        "braidwood" : "http://www.bom.gov.au/nsw/forecasts/braidwood.shtml",
        "yass" : "http://www.bom.gov.au/nsw/forecasts/yass.shtml",
        "crookwell" : "http://www.bom.gov.au/nsw/forecasts/crookwell.shtml",
        "queanbeyan" : "http://www.bom.gov.au/nsw/forecasts/queanbeyan.shtml",
        "tamworth" : "http://www.bom.gov.au/nsw/forecasts/tamworth.shtml",
        "moree" : "http://www.bom.gov.au/nsw/forecasts/moree.shtml",
        "narrabri" : "http://www.bom.gov.au/nsw/forecasts/narrabri.shtml",
        "gunnedah" : "http://www.bom.gov.au/nsw/forecasts/gunnedah.shtml",
        "barraba" : "http://www.bom.gov.au/nsw/forecasts/barraba.shtml",
        "walgett" : "http://www.bom.gov.au/nsw/forecasts/walgett.shtml",
        "warialda" : "http://www.bom.gov.au/nsw/forecasts/warialda.shtml",
        "wee waa" : "http://www.bom.gov.au/nsw/forecasts/wee-waa.shtml",
        "quirindi" : "http://www.bom.gov.au/nsw/forecasts/quirindi.shtml",
        "dubbo" : "http://www.bom.gov.au/nsw/forecasts/dubbo.shtml",
        "coonabarabran" : "http://www.bom.gov.au/nsw/forecasts/coonabarabran.shtml",
        "parkes" : "http://www.bom.gov.au/nsw/forecasts/parkes.shtml",
        "west wyalong" : "http://www.bom.gov.au/nsw/forecasts/west-wyalong.shtml",
        "coonamble" : "http://www.bom.gov.au/nsw/forecasts/coonamble.shtml",
        "condobolin" : "http://www.bom.gov.au/nsw/forecasts/condobolin.shtml",
        "forbes" : "http://www.bom.gov.au/nsw/forecasts/forbes.shtml",
        "cowra" : "http://www.bom.gov.au/nsw/forecasts/cowra.shtml",
        "lake cargelligo" : "http://www.bom.gov.au/nsw/forecasts/lake-cargelligo.shtml",
        "nyngan" : "http://www.bom.gov.au/nsw/forecasts/nyngan.shtml",
        "temora" : "http://www.bom.gov.au/nsw/forecasts/temora.shtml",
        "narromine" : "http://www.bom.gov.au/nsw/forecasts/narromine.shtml",
        "gundagai" : "http://www.bom.gov.au/nsw/forecasts/gundagai.shtml",
        "young" : "http://www.bom.gov.au/nsw/forecasts/young.shtml",
        "tumbarumba" : "http://www.bom.gov.au/nsw/forecasts/tumbarumba.shtml",
        "cootamundra" : "http://www.bom.gov.au/nsw/forecasts/cootamundra.shtml",
        "tumut" : "http://www.bom.gov.au/nsw/forecasts/tumut.shtml",
        "wagga wagga" : "http://www.bom.gov.au/nsw/forecasts/waggawagga.shtml",
        "hay" : "http://www.bom.gov.au/nsw/forecasts/hay.shtml",
        "deniliquin" : "http://www.bom.gov.au/nsw/forecasts/deniliquin.shtml",
        "griffith" : "http://www.bom.gov.au/nsw/forecasts/griffith.shtml",
        "corowa" : "http://www.bom.gov.au/nsw/forecasts/corowa.shtml",
        "finley" : "http://www.bom.gov.au/nsw/forecasts/finley.shtml",
        "junee" : "http://www.bom.gov.au/nsw/forecasts/junee.shtml",
        "narrandera" : "http://www.bom.gov.au/nsw/forecasts/narrandera.shtml",
        "ivanhoe" : "http://www.bom.gov.au/nsw/forecasts/ivanhoe.shtml",
        "broken hill" : "http://www.bom.gov.au/nsw/forecasts/brokenhill.shtml",
        "wentworth" : "http://www.bom.gov.au/nsw/forecasts/wentworth.shtml",
        "balranald" : "http://www.bom.gov.au/nsw/forecasts/balranald.shtml",
        "lake mungo" : "http://www.bom.gov.au/nsw/forecasts/lake-mungo.shtml",
        "menindee" : "http://www.bom.gov.au/nsw/forecasts/menindee.shtml",
        "bourke" : "http://www.bom.gov.au/nsw/forecasts/bourke.shtml",
        "tibooburra" : "http://www.bom.gov.au/nsw/forecasts/tibooburra.shtml",
        "cobar" : "http://www.bom.gov.au/nsw/forecasts/cobar.shtml",
        "brewarrina" : "http://www.bom.gov.au/nsw/forecasts/brewarrina.shtml",
        "wilcannia" : "http://www.bom.gov.au/nsw/forecasts/wilcannia.shtml",
        "perisher valley" : "http://www.bom.gov.au/nsw/forecasts/perisher.shtml",
        "selwyn" : "http://www.bom.gov.au/nsw/forecasts/selwyn.shtml",
        "cooma" : "http://www.bom.gov.au/nsw/forecasts/cooma.shtml",
        "cabramurra" : "http://www.bom.gov.au/nsw/forecasts/cabramurra.shtml",
        "bombala" : "http://www.bom.gov.au/nsw/forecasts/bombala.shtml",
        "charlotte pass" : "http://www.bom.gov.au/nsw/forecasts/charlotte-pass.shtml",
        "thredbo top station" : "http://www.bom.gov.au/nsw/forecasts/thredbo.shtml",
        "jindabyne" : "http://www.bom.gov.au/nsw/forecasts/jindabyne.shtml",
        "mildura" : "http://www.bom.gov.au/vic/forecasts/mildura.shtml",
        "swan hill" : "http://www.bom.gov.au/vic/forecasts/swanhill.shtml",
        "kerang" : "http://www.bom.gov.au/vic/forecasts/kerang.shtml",
        "ouyen" : "http://www.bom.gov.au/vic/forecasts/ouyen.shtml",
        "birchip" : "http://www.bom.gov.au/vic/forecasts/birchip.shtml",
        "horsham" : "http://www.bom.gov.au/vic/forecasts/horsham.shtml",
        "stawell" : "http://www.bom.gov.au/vic/forecasts/stawell.shtml",
        "warracknabeal" : "http://www.bom.gov.au/vic/forecasts/warracknabeal.shtml",
        "nhill" : "http://www.bom.gov.au/vic/forecasts/nhill.shtml",
        "edenhope" : "http://www.bom.gov.au/vic/forecasts/edenhope.shtml",
        "bendigo" : "http://www.bom.gov.au/vic/forecasts/bendigo.shtml",
        "shepparton" : "http://www.bom.gov.au/vic/forecasts/shepparton.shtml",
        "echuca" : "http://www.bom.gov.au/vic/forecasts/echuca.shtml",
        "kyabram" : "http://www.bom.gov.au/vic/forecasts/kyabram.shtml",
        "tatura" : "http://www.bom.gov.au/vic/forecasts/tatura.shtml",
        "yarrawonga" : "http://www.bom.gov.au/vic/forecasts/yarrawonga.shtml",
        "redesdale" : "http://www.bom.gov.au/vic/forecasts/redesdale.shtml",
        "cobram" : "http://www.bom.gov.au/vic/forecasts/cobram.shtml",
        "seymour" : "http://www.bom.gov.au/vic/forecasts/seymour.shtml",
        "maryborough" : "http://www.bom.gov.au/vic/forecasts/maryborough.shtml",
        "castlemaine" : "http://www.bom.gov.au/vic/forecasts/castlemaine.shtml",
        "lake eildon" : "http://www.bom.gov.au/vic/forecasts/lakeeildon.shtml",
        "lake mountain" : "http://www.bom.gov.au/vic/forecasts/lake-mountain.shtml",
        "albury-wodonga" : "http://www.bom.gov.au/vic/forecasts/wodonga.shtml",
        "wangaratta" : "http://www.bom.gov.au/vic/forecasts/wangaratta.shtml",
        "mount buller" : "http://www.bom.gov.au/vic/forecasts/mountbuller.shtml",
        "mount hotham" : "http://www.bom.gov.au/vic/forecasts/mounthotham.shtml",
        "falls creek" : "http://www.bom.gov.au/vic/forecasts/fallscreek.shtml",
        "rutherglen" : "http://www.bom.gov.au/vic/forecasts/rutherglen.shtml",
        "benalla" : "http://www.bom.gov.au/vic/forecasts/benalla.shtml",
        "beechworth" : "http://www.bom.gov.au/vic/forecasts/beechworth.shtml",
        "corryong" : "http://www.bom.gov.au/vic/forecasts/corryong.shtml",
        "mansfield" : "http://www.bom.gov.au/vic/forecasts/mansfield.shtml",
        "warrnambool" : "http://www.bom.gov.au/vic/forecasts/warrnambool.shtml",
        "colac" : "http://www.bom.gov.au/vic/forecasts/colac.shtml",
        "ararat" : "http://www.bom.gov.au/vic/forecasts/ararat.shtml",
        "casterton" : "http://www.bom.gov.au/vic/forecasts/casterton.shtml",
        "hamilton" : "http://www.bom.gov.au/vic/forecasts/hamilton.shtml",
        "mortlake" : "http://www.bom.gov.au/vic/forecasts/mortlake.shtml",
        "heywood" : "http://www.bom.gov.au/vic/forecasts/heywood.shtml",
        "portland" : "http://www.bom.gov.au/vic/forecasts/portland.shtml",
        "port fairy" : "http://www.bom.gov.au/vic/forecasts/portfairy.shtml",
        "cape otway" : "http://www.bom.gov.au/vic/forecasts/capeotway.shtml",
        "weeaproinah" : "http://www.bom.gov.au/vic/forecasts/weeaproinah.shtml",
        "melbourne" : "http://www.bom.gov.au/vic/forecasts/melbourne.shtml",
        "geelong" : "http://www.bom.gov.au/vic/forecasts/geelong.shtml",
        "ballarat" : "http://www.bom.gov.au/vic/forecasts/ballarat.shtml",
        "avalon" : "http://www.bom.gov.au/vic/forecasts/avalon.shtml",
        "laverton" : "http://www.bom.gov.au/vic/forecasts/laverton.shtml",
        "tullamarine" : "http://www.bom.gov.au/vic/forecasts/tullamarine.shtml",
        "moorabbin" : "http://www.bom.gov.au/vic/forecasts/moorabbin.shtml",
        "scoresby" : "http://www.bom.gov.au/vic/forecasts/scoresby.shtml",
        "watsonia" : "http://www.bom.gov.au/vic/forecasts/watsonia.shtml",
        "mount dandenong" : "http://www.bom.gov.au/vic/forecasts/mountdandenong.shtml",
        "yarra glen" : "http://www.bom.gov.au/vic/forecasts/yarraglen.shtml",
        "frankston" : "http://www.bom.gov.au/vic/forecasts/frankston.shtml",
        "cranbourne" : "http://www.bom.gov.au/vic/forecasts/cranbourne.shtml",
        "mornington" : "http://www.bom.gov.au/vic/forecasts/mornington.shtml",
        "cerberus" : "http://www.bom.gov.au/vic/forecasts/cerberus.shtml",
        "phillip island" : "http://www.bom.gov.au/vic/forecasts/phillipisland.shtml",
        "rhyll" : "http://www.bom.gov.au/vic/forecasts/rhyll.shtml",
        "dandenong" : "http://www.bom.gov.au/vic/forecasts/dandenong.shtml",
        "aireys inlet" : "http://www.bom.gov.au/vic/forecasts/aireysinlet.shtml",
        "wonthaggi" : "http://www.bom.gov.au/vic/forecasts/wonthaggi.shtml",
        "gisborne" : "http://www.bom.gov.au/vic/forecasts/gisborne.shtml",
        "kyneton" : "http://www.bom.gov.au/vic/forecasts/kyneton.shtml",
        "melton" : "http://www.bom.gov.au/vic/forecasts/melton.shtml",
        "pakenham" : "http://www.bom.gov.au/vic/forecasts/pakenham.shtml",
        "sunbury" : "http://www.bom.gov.au/vic/forecasts/sunbury.shtml",
        "torquay" : "http://www.bom.gov.au/vic/forecasts/torquay.shtml",
        "latrobe valley" : "http://www.bom.gov.au/vic/forecasts/latrobevalley.shtml",
        "sale" : "http://www.bom.gov.au/vic/forecasts/sale.shtml",
        "drouin" : "http://www.bom.gov.au/vic/forecasts/drouin.shtml",
        "traralgon" : "http://www.bom.gov.au/vic/forecasts/traralgon.shtml",
        "wilsons promontory" : "http://www.bom.gov.au/vic/forecasts/wilsonspromontory.shtml",
        "mount baw baw" : "http://www.bom.gov.au/vic/forecasts/mountbawbaw.shtml",
        "leongatha" : "http://www.bom.gov.au/vic/forecasts/leongatha.shtml",
        "moe" : "http://www.bom.gov.au/vic/forecasts/moe.shtml",
        "warragul" : "http://www.bom.gov.au/vic/forecasts/warragul.shtml",
        "bairnsdale" : "http://www.bom.gov.au/vic/forecasts/bairnsdale.shtml",
        "orbost" : "http://www.bom.gov.au/vic/forecasts/orbost.shtml",
        "lakes entrance" : "http://www.bom.gov.au/vic/forecasts/lakesentrance.shtml",
        "mallacoota" : "http://www.bom.gov.au/vic/forecasts/mallacoota.shtml",
        "omeo" : "http://www.bom.gov.au/vic/forecasts/omeo.shtml",
        "beaudesert" : "http://www.bom.gov.au/qld/forecasts/beaudesert.shtml",
        "boonah" : "http://www.bom.gov.au/qld/forecasts/boonah.shtml",
        "brisbane" : "http://www.bom.gov.au/qld/forecasts/brisbane.shtml",
        "brisbane airport" : "http://www.bom.gov.au/qld/forecasts/brisbane-airport.shtml",
        "caloundra" : "http://www.bom.gov.au/qld/forecasts/caloundra.shtml",
        "chermside" : "http://www.bom.gov.au/qld/forecasts/chermside.shtml",
        "coolangatta" : "http://www.bom.gov.au/qld/forecasts/coolangatta.shtml",
        "coomera" : "http://www.bom.gov.au/qld/forecasts/coomera.shtml",
        "esk" : "http://www.bom.gov.au/qld/forecasts/esk.shtml",
        "ferny grove" : "http://www.bom.gov.au/qld/forecasts/ferny-grove.shtml",
        "gatton" : "http://www.bom.gov.au/qld/forecasts/gatton.shtml",
        "gold coast seaway" : "http://www.bom.gov.au/qld/forecasts/gold-coast-seaway.shtml",
        "ipswich" : "http://www.bom.gov.au/qld/forecasts/ipswich.shtml",
        "kenmore" : "http://www.bom.gov.au/qld/forecasts/kenmore.shtml",
        "laidley" : "http://www.bom.gov.au/qld/forecasts/laidley.shtml",
        "maleny" : "http://www.bom.gov.au/qld/forecasts/maleny.shtml",
        "logan central" : "http://www.bom.gov.au/qld/forecasts/logan-central.shtml",
        "manly" : "http://www.bom.gov.au/qld/forecasts/manly.shtml",
        "maroochydore" : "http://www.bom.gov.au/qld/forecasts/maroochydore.shtml",
        "mount gravatt" : "http://www.bom.gov.au/qld/forecasts/mount-gravatt.shtml",
        "nambour" : "http://www.bom.gov.au/qld/forecasts/nambour.shtml",
        "nerang" : "http://www.bom.gov.au/qld/forecasts/nerang.shtml",
        "noosa heads" : "http://www.bom.gov.au/qld/forecasts/noosa-heads.shtml",
        "oxley" : "http://www.bom.gov.au/qld/forecasts/oxley.shtml",
        "redcliffe" : "http://www.bom.gov.au/qld/forecasts/redcliffe.shtml",
        "robina" : "http://www.bom.gov.au/qld/forecasts/robina.shtml",
        "surfers paradise" : "http://www.bom.gov.au/qld/forecasts/surfers-paradise.shtml",
        "caboolture" : "http://www.bom.gov.au/qld/forecasts/caboolture.shtml",
        "dalby" : "http://www.bom.gov.au/qld/forecasts/dalby.shtml",
        "goondiwindi" : "http://www.bom.gov.au/qld/forecasts/goondiwindi.shtml",
        "toowoomba" : "http://www.bom.gov.au/qld/forecasts/toowoomba.shtml",
        "warwick" : "http://www.bom.gov.au/qld/forecasts/warwick.shtml",
        "chinchilla" : "http://www.bom.gov.au/qld/forecasts/chinchilla.shtml",
        "miles" : "http://www.bom.gov.au/qld/forecasts/miles.shtml",
        "oakey" : "http://www.bom.gov.au/qld/forecasts/oakey.shtml",
        "stanthorpe" : "http://www.bom.gov.au/qld/forecasts/stanthorpe.shtml",
        "bundaberg" : "http://www.bom.gov.au/qld/forecasts/bundaberg.shtml",
        "gympie" : "http://www.bom.gov.au/qld/forecasts/gympie.shtml",
        "hervey bay" : "http://www.bom.gov.au/qld/forecasts/hervey-bay.shtml",
        "kingaroy" : "http://www.bom.gov.au/qld/forecasts/kingaroy.shtml",
        "maryborough" : "http://www.bom.gov.au/qld/forecasts/maryborough.shtml",
        "gayndah" : "http://www.bom.gov.au/qld/forecasts/gayndah.shtml",
        "monto" : "http://www.bom.gov.au/qld/forecasts/monto.shtml",
        "gladstone" : "http://www.bom.gov.au/qld/forecasts/gladstone.shtml",
        "rockhampton" : "http://www.bom.gov.au/qld/forecasts/rockhampton.shtml",
        "biloela" : "http://www.bom.gov.au/qld/forecasts/biloela.shtml",
        "yeppoon" : "http://www.bom.gov.au/qld/forecasts/yeppoon.shtml",
        "emerald" : "http://www.bom.gov.au/qld/forecasts/emerald.shtml",
        "blackwater" : "http://www.bom.gov.au/qld/forecasts/blackwater.shtml",
        "clermont" : "http://www.bom.gov.au/qld/forecasts/clermont.shtml",
        "dysart" : "http://www.bom.gov.au/qld/forecasts/dysart.shtml",
        "moranbah" : "http://www.bom.gov.au/qld/forecasts/moranbah.shtml",
        "rolleston" : "http://www.bom.gov.au/qld/forecasts/rolleston.shtml",
        "springsure" : "http://www.bom.gov.au/qld/forecasts/springsure.shtml",
        "taroom" : "http://www.bom.gov.au/qld/forecasts/taroom.shtml",
        "mackay" : "http://www.bom.gov.au/qld/forecasts/mackay.shtml",
        "bowen" : "http://www.bom.gov.au/qld/forecasts/bowen.shtml",
        "carmila" : "http://www.bom.gov.au/qld/forecasts/carmila.shtml",
        "hamilton island" : "http://www.bom.gov.au/qld/forecasts/hamilton-island.shtml",
        "proserpine" : "http://www.bom.gov.au/qld/forecasts/proserpine.shtml",
        "townsville" : "http://www.bom.gov.au/qld/forecasts/townsville.shtml",
        "ayr" : "http://www.bom.gov.au/qld/forecasts/ayr.shtml",
        "ingham" : "http://www.bom.gov.au/qld/forecasts/ingham.shtml",
        "cairns" : "http://www.bom.gov.au/qld/forecasts/cairns.shtml",
        "atherton" : "http://www.bom.gov.au/qld/forecasts/atherton.shtml",
        "cardwell" : "http://www.bom.gov.au/qld/forecasts/cardwell.shtml",
        "cooktown" : "http://www.bom.gov.au/qld/forecasts/cooktown.shtml",
        "innisfail" : "http://www.bom.gov.au/qld/forecasts/innisfail.shtml",
        "mareeba" : "http://www.bom.gov.au/qld/forecasts/mareeba.shtml",
        "charters towers" : "http://www.bom.gov.au/qld/forecasts/charters-towers.shtml",
        "georgetown" : "http://www.bom.gov.au/qld/forecasts/georgetown.shtml",
        "hughenden" : "http://www.bom.gov.au/qld/forecasts/hughenden.shtml",
        "richmond" : "http://www.bom.gov.au/qld/forecasts/richmond.shtml",
        "weipa" : "http://www.bom.gov.au/qld/forecasts/weipa.shtml",
        "aurukun" : "http://www.bom.gov.au/qld/forecasts/aurukun.shtml",
        "coen" : "http://www.bom.gov.au/qld/forecasts/coen.shtml",
        "laura" : "http://www.bom.gov.au/qld/forecasts/laura.shtml",
        "lockhart river" : "http://www.bom.gov.au/qld/forecasts/lockhart-river.shtml",
        "palmerville" : "http://www.bom.gov.au/qld/forecasts/palmerville.shtml",
        "thursday island" : "http://www.bom.gov.au/qld/forecasts/thursday-island.shtml",
        "normanton" : "http://www.bom.gov.au/qld/forecasts/normanton.shtml",
        "burketown" : "http://www.bom.gov.au/qld/forecasts/burketown.shtml",
        "croydon" : "http://www.bom.gov.au/qld/forecasts/croydon.shtml",
        "doomadgee" : "http://www.bom.gov.au/qld/forecasts/doomadgee.shtml",
        "kowanyama" : "http://www.bom.gov.au/qld/forecasts/kowanyama.shtml",
        "mornington island" : "http://www.bom.gov.au/qld/forecasts/mornington-island.shtml",
        "mount isa" : "http://www.bom.gov.au/qld/forecasts/mount-isa.shtml",
        "camooweal" : "http://www.bom.gov.au/qld/forecasts/camooweal.shtml",
        "julia creek" : "http://www.bom.gov.au/qld/forecasts/julia-creek.shtml",
        "urandangi" : "http://www.bom.gov.au/qld/forecasts/urandangi.shtml",
        "cloncurry" : "http://www.bom.gov.au/qld/forecasts/cloncurry.shtml",
        "longreach" : "http://www.bom.gov.au/qld/forecasts/longreach.shtml",
        "barcaldine" : "http://www.bom.gov.au/qld/forecasts/barcaldine.shtml",
        "blackall" : "http://www.bom.gov.au/qld/forecasts/blackall.shtml",
        "isisford" : "http://www.bom.gov.au/qld/forecasts/isisford.shtml",
        "tambo" : "http://www.bom.gov.au/qld/forecasts/tambo.shtml",
        "winton" : "http://www.bom.gov.au/qld/forecasts/winton.shtml",
        "charleville" : "http://www.bom.gov.au/qld/forecasts/charleville.shtml",
        "roma" : "http://www.bom.gov.au/qld/forecasts/roma.shtml",
        "st george" : "http://www.bom.gov.au/qld/forecasts/st-george.shtml",
        "augathella" : "http://www.bom.gov.au/qld/forecasts/augathella.shtml",
        "bollon" : "http://www.bom.gov.au/qld/forecasts/bollon.shtml",
        "cunnamulla" : "http://www.bom.gov.au/qld/forecasts/cunnamulla.shtml",
        "dirranbandi" : "http://www.bom.gov.au/qld/forecasts/dirranbandi.shtml",
        "injune" : "http://www.bom.gov.au/qld/forecasts/injune.shtml",
        "surat" : "http://www.bom.gov.au/qld/forecasts/surat.shtml",
        "birdsville" : "http://www.bom.gov.au/qld/forecasts/birdsville.shtml",
        "bedourie" : "http://www.bom.gov.au/qld/forecasts/bedourie.shtml",
        "boulia" : "http://www.bom.gov.au/qld/forecasts/boulia.shtml",
        "quilpie" : "http://www.bom.gov.au/qld/forecasts/quilpie.shtml",
        "thargomindah" : "http://www.bom.gov.au/qld/forecasts/thargomindah.shtml",
        "windorah" : "http://www.bom.gov.au/qld/forecasts/windorah.shtml",
        "broome" : "http://www.bom.gov.au/wa/forecasts/broome.shtml",
        "derby" : "http://www.bom.gov.au/wa/forecasts/derby.shtml",
        "fitzroy crossing" : "http://www.bom.gov.au/wa/forecasts/fitzroy-crossing.shtml",
        "kalumburu" : "http://www.bom.gov.au/wa/forecasts/kalumburu.shtml",
        "wyndham" : "http://www.bom.gov.au/wa/forecasts/wyndham.shtml",
        "kununurra" : "http://www.bom.gov.au/wa/forecasts/kununurra.shtml",
        "argyle" : "http://www.bom.gov.au/wa/forecasts/argyle.shtml",
        "halls creek mo" : "http://www.bom.gov.au/wa/forecasts/halls-creek.shtml",
        "bidyadanga" : "http://www.bom.gov.au/wa/forecasts/bidyadanga.shtml",
        "wallal" : "http://www.bom.gov.au/wa/forecasts/wallal.shtml",
        "exmouth" : "http://www.bom.gov.au/wa/forecasts/exmouth.shtml",
        "onslow" : "http://www.bom.gov.au/wa/forecasts/onslow.shtml",
        "karratha" : "http://www.bom.gov.au/wa/forecasts/karratha.shtml",
        "roebourne" : "http://www.bom.gov.au/wa/forecasts/roebourne.shtml",
        "port hedland" : "http://www.bom.gov.au/wa/forecasts/port-hedland.shtml",
        "marble bar" : "http://www.bom.gov.au/wa/forecasts/marble-bar.shtml",
        "paraburdoo" : "http://www.bom.gov.au/wa/forecasts/paraburdoo.shtml",
        "tom price" : "http://www.bom.gov.au/wa/forecasts/tom-price.shtml",
        "newman" : "http://www.bom.gov.au/wa/forecasts/newman.shtml",
        "barrow island" : "http://www.bom.gov.au/wa/forecasts/barrow-island.shtml",
        "dampier" : "http://www.bom.gov.au/wa/forecasts/dampier.shtml",
        "pannawonica" : "http://www.bom.gov.au/wa/forecasts/pannawonica.shtml",
        "telfer" : "http://www.bom.gov.au/wa/forecasts/telfer.shtml",
        "carnarvon" : "http://www.bom.gov.au/wa/forecasts/carnarvon.shtml",
        "coral bay" : "http://www.bom.gov.au/wa/forecasts/coral-bay.shtml",
        "meekatharra" : "http://www.bom.gov.au/wa/forecasts/meekatharra.shtml",
        "denham" : "http://www.bom.gov.au/wa/forecasts/denham.shtml",
        "gascoyne junction" : "http://www.bom.gov.au/wa/forecasts/gascoyne-junction.shtml",
        "mount magnet" : "http://www.bom.gov.au/wa/forecasts/mount-magnet.shtml",
        "mount augustus" : "http://www.bom.gov.au/wa/forecasts/mount-augustus.shtml",
        "murchison" : "http://www.bom.gov.au/wa/forecasts/murchison.shtml",
        "paynes find" : "http://www.bom.gov.au/wa/forecasts/paynes-find.shtml",
        "yalgoo" : "http://www.bom.gov.au/wa/forecasts/yalgoo.shtml",
        "kalgoorlie" : "http://www.bom.gov.au/wa/forecasts/kalgoorlie.shtml",
        "leonora" : "http://www.bom.gov.au/wa/forecasts/leonora.shtml",
        "laverton" : "http://www.bom.gov.au/wa/forecasts/laverton.shtml",
        "leinster" : "http://www.bom.gov.au/wa/forecasts/leinster.shtml",
        "norseman" : "http://www.bom.gov.au/wa/forecasts/norseman.shtml",
        "coolgardie" : "http://www.bom.gov.au/wa/forecasts/coolgardie.shtml",
        "kambalda" : "http://www.bom.gov.au/wa/forecasts/kambalda.shtml",
        "wiluna" : "http://www.bom.gov.au/wa/forecasts/wiluna.shtml",
        "eucla" : "http://www.bom.gov.au/wa/forecasts/eucla.shtml",
        "balladonia" : "http://www.bom.gov.au/wa/forecasts/balladonia.shtml",
        "cocklebiddy" : "http://www.bom.gov.au/wa/forecasts/cocklebiddy.shtml",
        "balgo hill" : "http://www.bom.gov.au/wa/forecasts/balgo-hill.shtml",
        "kiwirrkurra" : "http://www.bom.gov.au/wa/forecasts/kiwirrkurra.shtml",
        "warburton" : "http://www.bom.gov.au/wa/forecasts/warburton.shtml",
        "kalbarri" : "http://www.bom.gov.au/wa/forecasts/kalbarri.shtml",
        "geraldton" : "http://www.bom.gov.au/wa/forecasts/geraldton.shtml",
        "jurien bay" : "http://www.bom.gov.au/wa/forecasts/jurien-bay.shtml",
        "morawa" : "http://www.bom.gov.au/wa/forecasts/morawa.shtml",
        "moora" : "http://www.bom.gov.au/wa/forecasts/moora.shtml",
        "badgingarra" : "http://www.bom.gov.au/wa/forecasts/badgingarra.shtml",
        "carnamah" : "http://www.bom.gov.au/wa/forecasts/carnamah.shtml",
        "dongara" : "http://www.bom.gov.au/wa/forecasts/dongara.shtml",
        "eneabba" : "http://www.bom.gov.au/wa/forecasts/eneabba.shtml",
        "mullewa" : "http://www.bom.gov.au/wa/forecasts/mullewa.shtml",
        "northampton" : "http://www.bom.gov.au/wa/forecasts/northampton.shtml",
        "ellenbrook" : "http://www.bom.gov.au/wa/forecasts/ellenbrook.shtml",
        "yanchep" : "http://www.bom.gov.au/wa/forecasts/yanchep.shtml",
        "perth" : "http://www.bom.gov.au/wa/forecasts/perth.shtml",
        "joondalup" : "http://www.bom.gov.au/wa/forecasts/joondalup.shtml",
        "scarborough" : "http://www.bom.gov.au/wa/forecasts/scarborough.shtml",
        "fremantle" : "http://www.bom.gov.au/wa/forecasts/fremantle.shtml",
        "rockingham" : "http://www.bom.gov.au/wa/forecasts/rockingham.shtml",
        "midland" : "http://www.bom.gov.au/wa/forecasts/midland.shtml",
        "kalamunda" : "http://www.bom.gov.au/wa/forecasts/kalamunda.shtml",
        "armadale" : "http://www.bom.gov.au/wa/forecasts/armadale.shtml",
        "swanbourne" : "http://www.bom.gov.au/wa/forecasts/swanbourne.shtml",
        "rottnest island" : "http://www.bom.gov.au/wa/forecasts/rottnest-island.shtml",
        "mandurah" : "http://www.bom.gov.au/wa/forecasts/mandurah.shtml",
        "pinjarra" : "http://www.bom.gov.au/wa/forecasts/pinjarra.shtml",
        "gingin" : "http://www.bom.gov.au/wa/forecasts/gingin.shtml",
        "lancelin" : "http://www.bom.gov.au/wa/forecasts/lancelin.shtml",
        "bunbury" : "http://www.bom.gov.au/wa/forecasts/bunbury.shtml",
        "busselton" : "http://www.bom.gov.au/wa/forecasts/busselton.shtml",
        "margaret river" : "http://www.bom.gov.au/wa/forecasts/margaret-river.shtml",
        "augusta" : "http://www.bom.gov.au/wa/forecasts/augusta.shtml",
        "bridgetown" : "http://www.bom.gov.au/wa/forecasts/bridgetown.shtml",
        "collie" : "http://www.bom.gov.au/wa/forecasts/collie.shtml",
        "manjimup" : "http://www.bom.gov.au/wa/forecasts/manjimup.shtml",
        "boyup brook" : "http://www.bom.gov.au/wa/forecasts/boyup-brook.shtml",
        "pemberton" : "http://www.bom.gov.au/wa/forecasts/pemberton.shtml",
        "yallingup" : "http://www.bom.gov.au/wa/forecasts/yallingup.shtml",
        "harvey" : "http://www.bom.gov.au/wa/forecasts/harvey.shtml",
        "walpole" : "http://www.bom.gov.au/wa/forecasts/walpole.shtml",
        "windy harbour" : "http://www.bom.gov.au/wa/forecasts/wind-harbour.shtml",
        "albany" : "http://www.bom.gov.au/wa/forecasts/albany.shtml",
        "denmark" : "http://www.bom.gov.au/wa/forecasts/denmark.shtml",
        "mount barker" : "http://www.bom.gov.au/wa/forecasts/mount-barker.shtml",
        "jerramungup" : "http://www.bom.gov.au/wa/forecasts/jerramungup.shtml",
        "bremer bay" : "http://www.bom.gov.au/wa/forecasts/bremer-bay.shtml",
        "gnowangerup" : "http://www.bom.gov.au/wa/forecasts/gnowangerup.shtml",
        "esperance" : "http://www.bom.gov.au/wa/forecasts/esperance.shtml",
        "ravensthorpe" : "http://www.bom.gov.au/wa/forecasts/ravensthorpe.shtml",
        "hopetoun" : "http://www.bom.gov.au/wa/forecasts/hopetoun.shtml",
        "salmon gums" : "http://www.bom.gov.au/wa/forecasts/salmon-gums.shtml",
        "narrogin" : "http://www.bom.gov.au/wa/forecasts/narrogin.shtml",
        "katanning" : "http://www.bom.gov.au/wa/forecasts/katanning.shtml",
        "lake grace" : "http://www.bom.gov.au/wa/forecasts/lake-grace.shtml",
        "hyden" : "http://www.bom.gov.au/wa/forecasts/hyden.shtml",
        "brookton" : "http://www.bom.gov.au/wa/forecasts/brookton.shtml",
        "corrigin" : "http://www.bom.gov.au/wa/forecasts/corrigin.shtml",
        "wagin" : "http://www.bom.gov.au/wa/forecasts/wagin.shtml",
        "dalwallinu" : "http://www.bom.gov.au/wa/forecasts/dalwallinu.shtml",
        "northam" : "http://www.bom.gov.au/wa/forecasts/northam.shtml",
        "merredin" : "http://www.bom.gov.au/wa/forecasts/merredin.shtml",
        "southern cross" : "http://www.bom.gov.au/wa/forecasts/southern-cross.shtml",
        "cunderdin" : "http://www.bom.gov.au/wa/forecasts/cunderdin.shtml",
        "dowerin" : "http://www.bom.gov.au/wa/forecasts/dowerin.shtml",
        "mukinbudin" : "http://www.bom.gov.au/wa/forecasts/mukinbudin.shtml",
        "kellerberrin" : "http://www.bom.gov.au/wa/forecasts/kellerberrin.shtml",
        "wongan hills" : "http://www.bom.gov.au/wa/forecasts/wongan-hills.shtml",
        "york" : "http://www.bom.gov.au/wa/forecasts/york.shtml",
        "adelaide" : "http://www.bom.gov.au/sa/forecasts/adelaide.shtml",
        "elizabeth" : "http://www.bom.gov.au/sa/forecasts/elizabeth.shtml",
        "glenelg" : "http://www.bom.gov.au/sa/forecasts/glenelg.shtml",
        "noarlunga" : "http://www.bom.gov.au/sa/forecasts/noarlunga.shtml",
        "nuriootpa" : "http://www.bom.gov.au/sa/forecasts/nuriootpa.shtml",
        "victor harbor" : "http://www.bom.gov.au/sa/forecasts/victor-harbor.shtml",
        "mount barker" : "http://www.bom.gov.au/sa/forecasts/mount-barker.shtml",
        "parawa" : "http://www.bom.gov.au/sa/forecasts/parawa.shtml",
        "stirling" : "http://www.bom.gov.au/sa/forecasts/stirling.shtml",
        "strathalbyn" : "http://www.bom.gov.au/sa/forecasts/strathalbyn.shtml",
        "maitland" : "http://www.bom.gov.au/sa/forecasts/maitland.shtml",
        "edithburgh" : "http://www.bom.gov.au/sa/forecasts/edithburgh.shtml",
        "kadina" : "http://www.bom.gov.au/sa/forecasts/kadina.shtml",
        "minlaton" : "http://www.bom.gov.au/sa/forecasts/minlaton.shtml",
        "stenhouse bay" : "http://www.bom.gov.au/sa/forecasts/stenhousebay.shtml",
        "kingscote" : "http://www.bom.gov.au/sa/forecasts/kingscote.shtml",
        "parndana" : "http://www.bom.gov.au/sa/forecasts/parndana.shtml",
        "mount gambier" : "http://www.bom.gov.au/sa/forecasts/mount-gambier.shtml",
        "naracoorte" : "http://www.bom.gov.au/sa/forecasts/naracoorte.shtml",
        "coonawarra" : "http://www.bom.gov.au/sa/forecasts/coonawarra.shtml",
        "robe" : "http://www.bom.gov.au/sa/forecasts/robe.shtml",
        "keith" : "http://www.bom.gov.au/sa/forecasts/keith.shtml",
        "bordertown" : "http://www.bom.gov.au/sa/forecasts/bordertown.shtml",
        "meningie" : "http://www.bom.gov.au/sa/forecasts/meningie.shtml",
        "murray bridge" : "http://www.bom.gov.au/sa/forecasts/murray-bridge.shtml",
        "karoonda" : "http://www.bom.gov.au/sa/forecasts/karoonda.shtml",
        "lameroo" : "http://www.bom.gov.au/sa/forecasts/lameroo.shtml",
        "renmark" : "http://www.bom.gov.au/sa/forecasts/renmark.shtml",
        "waikerie" : "http://www.bom.gov.au/sa/forecasts/waikerie.shtml",
        "port pirie" : "http://www.bom.gov.au/sa/forecasts/port-pirie.shtml",
        "jamestown" : "http://www.bom.gov.au/sa/forecasts/jamestown.shtml",
        "clare" : "http://www.bom.gov.au/sa/forecasts/clare.shtml",
        "roseworthy" : "http://www.bom.gov.au/sa/forecasts/roseworthy.shtml",
        "snowtown" : "http://www.bom.gov.au/sa/forecasts/snowtown.shtml",
        "hawker" : "http://www.bom.gov.au/sa/forecasts/hawker.shtml",
        "port augusta" : "http://www.bom.gov.au/sa/forecasts/port-augusta.shtml",
        "orroroo" : "http://www.bom.gov.au/sa/forecasts/orroroo.shtml",
        "whyalla" : "http://www.bom.gov.au/sa/forecasts/whyalla.shtml",
        "cleve" : "http://www.bom.gov.au/sa/forecasts/cleve.shtml",
        "kimba" : "http://www.bom.gov.au/sa/forecasts/kimba.shtml",
        "port lincoln" : "http://www.bom.gov.au/sa/forecasts/port-lincoln.shtml",
        "coffin bay" : "http://www.bom.gov.au/sa/forecasts/coffinbay.shtml",
        "cummins" : "http://www.bom.gov.au/sa/forecasts/cummins.shtml",
        "ceduna" : "http://www.bom.gov.au/sa/forecasts/ceduna.shtml",
        "wudinna" : "http://www.bom.gov.au/sa/forecasts/wudinna.shtml",
        "elliston" : "http://www.bom.gov.au/sa/forecasts/elliston.shtml",
        "nullarbor" : "http://www.bom.gov.au/sa/forecasts/nullarbor.shtml",
        "coober pedy" : "http://www.bom.gov.au/sa/forecasts/coober-pedy.shtml",
        "roxby downs" : "http://www.bom.gov.au/sa/forecasts/roxby-downs.shtml",
        "woomera" : "http://www.bom.gov.au/sa/forecasts/woomera.shtml",
        "pukatja/ernabella" : "http://www.bom.gov.au/sa/forecasts/ernabella.shtml",
        "marla" : "http://www.bom.gov.au/sa/forecasts/marla.shtml",
        "oak valley" : "http://www.bom.gov.au/sa/forecasts/oakvalley.shtml",
        "tarcoola" : "http://www.bom.gov.au/sa/forecasts/tarcoola.shtml",
        "leigh creek" : "http://www.bom.gov.au/sa/forecasts/leigh-creek.shtml",
        "marree" : "http://www.bom.gov.au/sa/forecasts/marree.shtml",
        "moomba" : "http://www.bom.gov.au/sa/forecasts/moomba.shtml",
        "oodnadatta" : "http://www.bom.gov.au/sa/forecasts/oodnadatta.shtml",
        "yunta" : "http://www.bom.gov.au/sa/forecasts/yunta.shtml",
        "currie" : "http://www.bom.gov.au/tas/forecasts/currie.shtml",
        "burnie" : "http://www.bom.gov.au/tas/forecasts/burnie.shtml",
        "deloraine" : "http://www.bom.gov.au/tas/forecasts/deloraine.shtml",
        "devonport" : "http://www.bom.gov.au/tas/forecasts/devonport.shtml",
        "latrobe" : "http://www.bom.gov.au/tas/forecasts/latrobe.shtml",
        "marrawah" : "http://www.bom.gov.au/tas/forecasts/marrawah.shtml",
        "penguin" : "http://www.bom.gov.au/tas/forecasts/penguin.shtml",
        "port sorell" : "http://www.bom.gov.au/tas/forecasts/port-sorell.shtml",
        "railton" : "http://www.bom.gov.au/tas/forecasts/railton.shtml",
        "smithton" : "http://www.bom.gov.au/tas/forecasts/smithton.shtml",
        "stanley" : "http://www.bom.gov.au/tas/forecasts/stanley.shtml",
        "ulverstone" : "http://www.bom.gov.au/tas/forecasts/ulverstone.shtml",
        "wynyard" : "http://www.bom.gov.au/tas/forecasts/wynyard.shtml",
        "sheffield" : "http://www.bom.gov.au/tas/forecasts/sheffield.shtml",
        "launceston" : "http://www.bom.gov.au/tas/forecasts/launceston.shtml",
        "cressy" : "http://www.bom.gov.au/tas/forecasts/cressie.shtml",
        "evandale" : "http://www.bom.gov.au/tas/forecasts/evandale.shtml",
        "exeter" : "http://www.bom.gov.au/tas/forecasts/exeter.shtml",
        "george town" : "http://www.bom.gov.au/tas/forecasts/georgetown.shtml",
        "mowbray" : "http://www.bom.gov.au/tas/forecasts/mowbray.shtml",
        "prospect" : "http://www.bom.gov.au/tas/forecasts/prospect.shtml",
        "the corner" : "http://www.bom.gov.au/tas/forecasts/the-corner.shtml",
        "whitemark" : "http://www.bom.gov.au/tas/forecasts/whitemark.shtml",
        "ben lomond" : "http://www.bom.gov.au/tas/forecasts/ben-lomond.shtml",
        "bridport" : "http://www.bom.gov.au/tas/forecasts/bridport.shtml",
        "scottsdale" : "http://www.bom.gov.au/tas/forecasts/scottsdale.shtml",
        "bothwell" : "http://www.bom.gov.au/tas/forecasts/bothwell.shtml",
        "cradle valley" : "http://www.bom.gov.au/tas/forecasts/cradlevalley.shtml",
        "liawenee" : "http://www.bom.gov.au/tas/forecasts/liawenee.shtml",
        "lake st clair" : "http://www.bom.gov.au/tas/forecasts/lakestclair.shtml",
        "new pelion hut" : "http://www.bom.gov.au/tas/forecasts/new-pelion-hut.shtml",
        "tarraleah" : "http://www.bom.gov.au/tas/forecasts/tarraleah.shtml",
        "strahan" : "http://www.bom.gov.au/tas/forecasts/strahan.shtml",
        "maydena" : "http://www.bom.gov.au/tas/forecasts/maydena.shtml",
        "melaleuca" : "http://www.bom.gov.au/tas/forecasts/melaleuca.shtml",
        "mount field" : "http://www.bom.gov.au/tas/forecasts/mount-field.shtml",
        "queenstown" : "http://www.bom.gov.au/tas/forecasts/queenstown.shtml",
        "rosebery" : "http://www.bom.gov.au/tas/forecasts/rosebery.shtml",
        "strathgordon" : "http://www.bom.gov.au/tas/forecasts/strathgordon.shtml",
        "waratah" : "http://www.bom.gov.au/tas/forecasts/waratah.shtml",
        "zeehan" : "http://www.bom.gov.au/tas/forecasts/zeehan.shtml",
        "campbell town" : "http://www.bom.gov.au/tas/forecasts/cambelltown.shtml",
        "oatlands" : "http://www.bom.gov.au/tas/forecasts/oatlands.shtml",
        "ross" : "http://www.bom.gov.au/tas/forecasts/ross.shtml",
        "tunnack" : "http://www.bom.gov.au/tas/forecasts/tunnack.shtml",
        "bicheno" : "http://www.bom.gov.au/tas/forecasts/bicheno.shtml",
        "coles bay" : "http://www.bom.gov.au/tas/forecasts/coles-bay.shtml",
        "st helens" : "http://www.bom.gov.au/tas/forecasts/sthelens.shtml",
        "fingal" : "http://www.bom.gov.au/tas/forecasts/fingal.shtml",
        "orford" : "http://www.bom.gov.au/tas/forecasts/orford.shtml",
        "st marys" : "http://www.bom.gov.au/tas/forecasts/st-marys.shtml",
        "maria island" : "http://www.bom.gov.au/tas/forecasts/maria-island.shtml",
        "swansea" : "http://www.bom.gov.au/tas/forecasts/swansea.shtml",
        "new norfolk" : "http://www.bom.gov.au/tas/forecasts/newnorfolk.shtml",
        "ouse" : "http://www.bom.gov.au/tas/forecasts/ouse.shtml",
        "campania" : "http://www.bom.gov.au/tas/forecasts/campania.shtml",
        "hobart" : "http://www.bom.gov.au/tas/forecasts/hobart.shtml",
        "kunanyi/mount wellington" : "http://www.bom.gov.au/tas/forecasts/mtwellington.shtml",
        "adventure bay" : "http://www.bom.gov.au/tas/forecasts/adventure-bay.shtml",
        "bellerive" : "http://www.bom.gov.au/tas/forecasts/bellerive.shtml",
        "brighton" : "http://www.bom.gov.au/tas/forecasts/brighton.shtml",
        "cygnet" : "http://www.bom.gov.au/tas/forecasts/cygnet.shtml",
        "dover" : "http://www.bom.gov.au/tas/forecasts/dover.shtml",
        "geeveston" : "http://www.bom.gov.au/tas/forecasts/geeveston.shtml",
        "glenorchy" : "http://www.bom.gov.au/tas/forecasts/glenorchy.shtml",
        "huonville" : "http://www.bom.gov.au/tas/forecasts/huonville.shtml",
        "kingston" : "http://www.bom.gov.au/tas/forecasts/kingston.shtml",
        "port arthur" : "http://www.bom.gov.au/tas/forecasts/portarthur.shtml",
        "richmond" : "http://www.bom.gov.au/tas/forecasts/richmond.shtml",
        "sorell" : "http://www.bom.gov.au/tas/forecasts/sorell.shtml",
        "acacia hills" : "http://www.bom.gov.au/nt/forecasts/acacia-hills.shtml",
        "adelaide river" : "http://www.bom.gov.au/nt/forecasts/adelaide-river.shtml",
        "bark hut" : "http://www.bom.gov.au/nt/forecasts/bark-hut.shtml",
        "batchelor" : "http://www.bom.gov.au/nt/forecasts/batchelor.shtml",
        "belyuen" : "http://www.bom.gov.au/nt/forecasts/belyuen.shtml",
        "berrimah" : "http://www.bom.gov.au/nt/forecasts/berrimah.shtml",
        "berry springs" : "http://www.bom.gov.au/nt/forecasts/berry-springs.shtml",
        "coolalinga" : "http://www.bom.gov.au/nt/forecasts/coolalinga.shtml",
        "darwin airport" : "http://www.bom.gov.au/nt/forecasts/darwin-airport.shtml",
        "darwin" : "http://www.bom.gov.au/nt/forecasts/darwin.shtml",
        "dorisvale" : "http://www.bom.gov.au/nt/forecasts/dorisvale.shtml",
        "dundee beach" : "http://www.bom.gov.au/nt/forecasts/dundee-beach.shtml",
        "florence falls" : "http://www.bom.gov.au/nt/forecasts/florence-falls.shtml",
        "howard springs" : "http://www.bom.gov.au/nt/forecasts/howard-springs.shtml",
        "humpty doo" : "http://www.bom.gov.au/nt/forecasts/humpty-doo.shtml",
        "leanyer" : "http://www.bom.gov.au/nt/forecasts/leanyer.shtml",
        "nauiyu" : "http://www.bom.gov.au/nt/forecasts/nauiyu.shtml",
        "nightcliff" : "http://www.bom.gov.au/nt/forecasts/nightcliff.shtml",
        "noonamah" : "http://www.bom.gov.au/nt/forecasts/noonamah.shtml",
        "palumpa" : "http://www.bom.gov.au/nt/forecasts/palumpa.shtml",
        "palmerston" : "http://www.bom.gov.au/nt/forecasts/palmerston.shtml",
        "peppimenarti" : "http://www.bom.gov.au/nt/forecasts/peppimenarti.shtml",
        "pine creek" : "http://www.bom.gov.au/nt/forecasts/pine-creek.shtml",
        "surprise creek falls" : "http://www.bom.gov.au/nt/forecasts/surprise-creek-falls.shtml",
        "tjaynera falls" : "http://www.bom.gov.au/nt/forecasts/tjaynera-falls.shtml",
        "wadeye" : "http://www.bom.gov.au/nt/forecasts/wadeye.shtml",
        "wagait beach" : "http://www.bom.gov.au/nt/forecasts/wagait-beach.shtml",
        "wangi falls" : "http://www.bom.gov.au/nt/forecasts/wangi-falls.shtml",
        "wurrumiyanga" : "http://www.bom.gov.au/nt/forecasts/wurrumiyanga.shtml",
        "milikapiti" : "http://www.bom.gov.au/nt/forecasts/milikapiti.shtml",
        "pirlangimpi" : "http://www.bom.gov.au/nt/forecasts/pirlangimpi.shtml",
        "jabiru" : "http://www.bom.gov.au/nt/forecasts/jabiru.shtml",
        "maningrida" : "http://www.bom.gov.au/nt/forecasts/maningrida.shtml",
        "nhulunbuy" : "http://www.bom.gov.au/nt/forecasts/nhulunbuy.shtml",
        "alyangula" : "http://www.bom.gov.au/nt/forecasts/alyangula.shtml",
        "angurugu" : "http://www.bom.gov.au/nt/forecasts/angurugu.shtml",
        "barunga" : "http://www.bom.gov.au/nt/forecasts/barunga.shtml",
        "beswick" : "http://www.bom.gov.au/nt/forecasts/beswick.shtml",
        "birany birany" : "http://www.bom.gov.au/nt/forecasts/birany-birany.shtml",
        "bulman" : "http://www.bom.gov.au/nt/forecasts/bulman.shtml",
        "burrunggui" : "http://www.bom.gov.au/nt/forecasts/burrunggui.shtml",
        "cooinda" : "http://www.bom.gov.au/nt/forecasts/cooinda.shtml",
        "galiwinku" : "http://www.bom.gov.au/nt/forecasts/galiwinku.shtml",
        "gapuwiyak" : "http://www.bom.gov.au/nt/forecasts/gapuwiyak.shtml",
        "gunbalanya" : "http://www.bom.gov.au/nt/forecasts/gunbalanya.shtml",
        "gunlom" : "http://www.bom.gov.au/nt/forecasts/gunlom.shtml",
        "gunyangara" : "http://www.bom.gov.au/nt/forecasts/gunyangara.shtml",
        "jim jim falls" : "http://www.bom.gov.au/nt/forecasts/jim-jim-falls.shtml",
        "milingimbi" : "http://www.bom.gov.au/nt/forecasts/milingimbi.shtml",
        "minjilang" : "http://www.bom.gov.au/nt/forecasts/minjilang.shtml",
        "ngayawili" : "http://www.bom.gov.au/nt/forecasts/ngayawili.shtml",
        "ngukurr" : "http://www.bom.gov.au/nt/forecasts/ngukurr.shtml",
        "nhulunbuy airport" : "http://www.bom.gov.au/nt/forecasts/nhulunbuy-airport.shtml",
        "numbulwar" : "http://www.bom.gov.au/nt/forecasts/numbulwar.shtml",
        "ramingining" : "http://www.bom.gov.au/nt/forecasts/ramingining.shtml",
        "twin falls" : "http://www.bom.gov.au/nt/forecasts/twin-falls.shtml",
        "ubirr" : "http://www.bom.gov.au/nt/forecasts/ubirr.shtml",
        "warruwi" : "http://www.bom.gov.au/nt/forecasts/warruwi.shtml",
        "yirrkala" : "http://www.bom.gov.au/nt/forecasts/yirrkala.shtml",
        "katherine" : "http://www.bom.gov.au/nt/forecasts/katherine.shtml",
        "borroloola" : "http://www.bom.gov.au/nt/forecasts/borroloola.shtml",
        "daly waters" : "http://www.bom.gov.au/nt/forecasts/daly-waters.shtml",
        "mataranka" : "http://www.bom.gov.au/nt/forecasts/mataranka.shtml",
        "wollogorang" : "http://www.bom.gov.au/nt/forecasts/wollogorang.shtml",
        "daguragu" : "http://www.bom.gov.au/nt/forecasts/daguragu.shtml",
        "newry" : "http://www.bom.gov.au/nt/forecasts/newry.shtml",
        "timber creek" : "http://www.bom.gov.au/nt/forecasts/timber-creek.shtml",
        "tennant creek" : "http://www.bom.gov.au/nt/forecasts/tennant-creek.shtml",
        "ali curung" : "http://www.bom.gov.au/nt/forecasts/ali-curung.shtml",
        "alpurrurulam" : "http://www.bom.gov.au/nt/forecasts/alpurrurulam.shtml",
        "ampilatwatja" : "http://www.bom.gov.au/nt/forecasts/ampilatwatja.shtml",
        "avon downs" : "http://www.bom.gov.au/nt/forecasts/avon-downs.shtml",
        "barrow creek" : "http://www.bom.gov.au/nt/forecasts/barrow-creek.shtml",
        "cresswell downs" : "http://www.bom.gov.au/nt/forecasts/cresswell-downs.shtml",
        "elliott" : "http://www.bom.gov.au/nt/forecasts/elliott.shtml",
        "alice springs" : "http://www.bom.gov.au/nt/forecasts/alice-springs.shtml",
        "alice springs airport" : "http://www.bom.gov.au/nt/forecasts/alice-springs-airport.shtml",
        "arltunga" : "http://www.bom.gov.au/nt/forecasts/arltunga.shtml",
        "finke" : "http://www.bom.gov.au/nt/forecasts/finke.shtml",
        "jervois" : "http://www.bom.gov.au/nt/forecasts/jervois.shtml",
        "kulgera" : "http://www.bom.gov.au/nt/forecasts/kulgera.shtml",
        "ross river" : "http://www.bom.gov.au/nt/forecasts/ross-river.shtml",
        "santa teresa" : "http://www.bom.gov.au/nt/forecasts/santa-teresa.shtml",
        "ti tree" : "http://www.bom.gov.au/nt/forecasts/ti-tree.shtml",
        "titjikala" : "http://www.bom.gov.au/nt/forecasts/titjikala.shtml",
        "yulara" : "http://www.bom.gov.au/nt/forecasts/yulara.shtml",
        "curtin springs" : "http://www.bom.gov.au/nt/forecasts/curtin-springs.shtml",
        "docker river" : "http://www.bom.gov.au/nt/forecasts/docker-river.shtml",
        "hermannsburg" : "http://www.bom.gov.au/nt/forecasts/hermannsburg.shtml",
        "papunya" : "http://www.bom.gov.au/nt/forecasts/papunya.shtml",
        "uluru" : "http://www.bom.gov.au/nt/forecasts/uluru.shtml",
        "watarrka" : "http://www.bom.gov.au/nt/forecasts/watarrka.shtml",
        "wulungurru" : "http://www.bom.gov.au/nt/forecasts/wulungurru.shtml",
        "lajamanu" : "http://www.bom.gov.au/nt/forecasts/lajamanu.shtml",
        "rabbit flat" : "http://www.bom.gov.au/nt/forecasts/rabbit-flat.shtml",
        "yuendumu" : "http://www.bom.gov.au/nt/forecasts/yuendumu.shtml"
    }