nickname: "imobot"
password: ""
hostname: "localhost"
port: 6667
#channels:
#  - name: "#general"
#    plugins:
#      - name: "Stats"
#        kwargs: {"url" : "http://stats.example.com"}
#      - name: "UrlTitles"
#      - name: "MagicEightBall"