nickname: "imobot"
password: ""
hostname: "irc.example.com"
port: 6667
channels:
  - name: "#general"
    plugins:
      - name: "Stats"
        url: "http://stats.example.com/"
      - name: "UrlTitles"
      - name: "MagicEightBall"